### PR TITLE
Fix Breaking Bugs, Code Clean Up, and More!

### PR DESCRIPTION
**Pull request by srhinos**
Apologies for massive PR but originally didn't intend to commit upstream but decided it was worthwhile regardless.

This achieves the following:

- Fixes common flake8 warnings
- Blacks the file
- Improves legibility of the code output file
- Allows users to swap between chromium and firefox with a kwarg (idk why chromium is 100% broken for me on my Windows pc but it is)
- Add output on run to denote already claimed offers
- Add error handling for direct game claims that was breaking this beforehand (not an actual fix, just prevents crashing)

EDIT: Got bored and added more stuff:
- Added a cool countdown while in loop mode(pls rip this out if too hacky)
- Cleaned up the code around the loop area to be more readable.

### CODE REVIEW

**Comment by srhinos** [comment]
As a note, this fixes https://github.com/sibalzer/primelooter/issues/23

**Review by sibalzer — APPROVED** [review]
one lint error in ci but looks good enough for me.

**Comment by sibalzer** [comment]
Nice! I can't validate it against Amazon unfortunately, as I cancelled my Prime subscription as mentioned in an issue already. But I will merge it anyway in the hope that everything is correct. Do you want to take over the repro? I would then archive this here and link your fork in the readme file.

**Comment by srhinos** [comment]
> Nice! I can't validate it against Amazon unfortunately, as I cancelled my Prime subscription as mentioned in an issue already. But I will merge it anyway in the hope that everything is correct. Do you want to take over the repro? I would then archive this here and link your fork in the readme file.

Nice, yeah totally fine with that! I'm gonna most likely be fixing it for myself for the foreseeable future so happy to just host the codebase moving forward! You did awesome work btw so hopefully if you pick up prime again we can merge it back upstream :)

**Comment by srhinos** [comment]
Going to open a PR on my fork to post the same recap of changes and merge it there then!

**Pull request closed without merging**
